#!/media/joshua/Data2/Devops/ansible/venv/bin/ansible-playbook
- name: Install
  hosts: all
  remote_user: test
  become: true
  become_user: root

  tasks:
    - name: Debug demo
      debug:
        msg: "hello"
        verbosity: 1