#!/media/joshua/Data2/Devops/ansible/venv/bin/ansible-playbook
- name: Variables demo
  hosts: all
  remote_user: test
  become: true
  become_user: root

  vars:
    a: "hElLo"
  
  tasks:
    - name: methods demo
      debug:
        msg:
          - "{{a|upper}}"
          - "{{a.lower()}}"